# Generated by Django 4.0.1 on 2022-01-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amounts',
            new_name='Amount',
        ),
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Modes',
            new_name='Mode',
        ),
        migrations.RenameModel(
            old_name='Periods',
            new_name='Period',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
